import Input from './Input/Input'
import InputCard from './InputCard'
import DropDown from './DropDown'
import Button from './Button'
import Select from './Select'
import FormHead from './FormHead'
import HomeCard from './HomeCard'
// import ProfilePicture from './ProfilePicture'
import MultipeChoice from './MultipeChoice'
import CheckBox from './CheckBox'
import RenameCard from './RenameCard'
import FormCard from './FormCard'
import AdminIndividualCard from './AdminIndividualCard'
import DataAdminCard from './DataAdminCard'
export {Input,InputCard,DropDown,Button,Select,FormHead,HomeCard,MultipeChoice,CheckBox,RenameCard,FormCard,AdminIndividualCard,DataAdminCard}